### ISSUE TITLE
Fix cookie opt-in on global website

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/websites#1]
Rachel tried to set up a plugin for a cookie consent banner. But it doesn't work correctly. The plugin sets some cookies but no other cookies (analytics) are set even after agreeing to it.

**Comment by RachL** [comment]
Thank you @mkllnk !

I'm leaving here what I had previously said on Slack:

I'm seeing that the cookie for this is correctly updated, but I don't know how to test that Matomo is checking this cookie correctly. I've used this page: https://matomo.org/faq/general/faq_157/ but maybe I've placed the check at the wrong place in the script.

**Comment by mkllnk** [comment]
Finally done! Please test.

It took me a while to figure out how it works but it was quite easy in the end. I did two things:

1. Deactivate Matomo plugin. Can we delete it?. It has two features:
  - Show a Matomo dashboard in Wordpress. We don't need that because we have much better features on our Matomo site, right?
  - Include the Matomo tracking script. We don't want that here because it ignores the cookie decision of the user.
2. Add the Matomo tracking script to the GDPR Cookie Consent plugin. The plugin will only load the script if the user agrees to cookies.

@RachL Do you agree with removing the Matomo plugin?

**Comment by RachL** [comment]
@mkllnk great! I've used the Matomo plugin because I thought it was the only way to install the tracking code. Then I've tried to put the cookies exception within this plugin, so the solution was actually to do the opposite : put the Matomo tracking code within the cookies policy plugin!

I've tested it and it looks great:

1. As long as you don't accept the cookies you are not tracked (can be changed but this is it for now)
2. Once you accept your are tracked
3. If you refuse, it stops tracking

This issue can now be closed and the plugin can be deleted 🎉
